# Generated by Django 2.2 on 2019-08-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
