# Generated by Django 2.2 on 2019-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190826_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BinaryField(choices=[(1, 'True'), (0, 'False')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Read')], default=0),
        ),
    ]
